### ISSUE TITLE
Unable to create jenkins image - permission denied

### ISSUE THREAD

**Issue by gokalper** [redhat-developer/jenkins-old-community-operator#154]
When trying to apply the below yaml file I get the following error in pod: 

`Error: error resolving dockerfile path: copying dockerfile: creating file: open /kaniko/Dockerfile: permission denied`

```
apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: jenkins-corp-image
spec:
  from:
    name: jenkins/jenkins
    tag: lts
  plugins:
  - name: kubernetes
  to:
    registry: default-route-openshift-image-registry.apps.ocp.domain.com
    name: jenkins-corp-image
    tag: latest
```

It looks like an issue due to needing to run as a root user but i can not set the security context as it fails to apply when attached to the spec:

```
  spec:
    securityContext:
      runAsUser: 0
      fsGroup: 0
```
